# -*- coding: utf-8 -*-
"""ElasticSearch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_xXPbU0ZNmkBEwg2-vFuYkYe0jwD5JE3
"""

import json

fop = []
with open('Chinesedata.json') as json_file:
    data = json.load(json_file)
    for line in data:
        output = {}
        output['id'] = line['id']
        output['cuisine'] = line['cuisine']
        fop.append(output)

with open('elasticdata_new.json','a') as jsonFile:
    json.dump(fop, jsonFile)

fop = []
bulk_format = { "index" : { "_index": "restaurants", "_type":"RESTAURANT"}}
with open('elasticdata_new.json') as json_file:
    data = json.load(json_file)
    for line in data:
        fop.append(bulk_format)
        output = {}
        output['id'] = line['id']
        output['cuisine'] = line['cuisine']
        fop.append(output)

with open('finaltestfile.json','a') as jsonFile:
    for line in fop:
        jsonFile.write(str(line))
        jsonFile.write("\n")

with open('finaltestfile.json','r') as jsonrFile:
    with open("finalbulk_data.json","a") as jsonFile:
        for line in jsonrFile:
            jsonFile.write(line.replace("\'","\""))